#!/usr/bin/env bash
set -euo pipefail

BACKEND_DOMAIN="${1:-https://salesauto-api-demo.trycloudflare.com}"
FRONTEND_DOMAIN="${2:-https://salesauto-frontend-demo.trycloudflare.com}"

cat > frontend/runtime-config.js <<CONFIG
// Generated by scripts/configure_disposable_domain.sh
window.__API_BASE_URL__ = '${BACKEND_DOMAIN}';
CONFIG

cat <<MSG
Disposable domain config applied.

Frontend runtime API URL:
  ${BACKEND_DOMAIN}

Set this in backend host environment variables:
  FRONTEND_ORIGIN=${FRONTEND_DOMAIN}

Then deploy frontend + backend and test:
  ./scripts/test_endpoints.sh ${BACKEND_DOMAIN}
MSG
